version: 0.2


phases:
  pre_build:
    commands:
      - mvn clean install
      - echo Maven clean in prebuild compeletd
  build:
    commands:
#      - docker build -t sprintbootfromawscd .
      - echo Maven build completed
  
  post_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 433852985439.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t testrepo .
      - docker tag testrepo:latest 433852985439.dkr.ecr.us-east-1.amazonaws.com/testrepo:latest
      - docker push 433852985439.dkr.ecr.us-east-1.amazonaws.com/testrepo:latest
#     - docker login --username ningle30 --password Nihar@123
#     - docker push ningle30/sprintbootfromawscd
      - echo POst Build completed on `date`
      
artifacts:
  files:
   - target/servicesdevops-0.0.1-SNAPSHOT.jar
#   - appspec.yml