version: 0.2


phases:
  pre_build:
    commands:
      - mvn clean install
      - echo Maven clean in prebuild compeletd
  build:
    commands:
      - docker build -t ningle30/sprintbootfromawscd .
      - echo Maven build completed
  
  post_build:
    commands:
      - docker login --username ningle30 --password Nihar@123
      - docker push ningle30/sprintbootfromawscd
      - echo POst Build completed on `date`
      
artifacts:
  files:

   - target/servicesdevops-0.0.1-SNAPSHOT.jar